<a href="https://colab.research.google.com/github/vanshchaudharyx/Python-Libraries/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy array object name->> ndarray<br>
----------------------------------<br>
d->dimension<br>
1-d-> one line<br>
2-d-> row and coloumn<br>
3-d-> multiple 2-d table<br>
Axis ---> dimension<br>
1-D array<br>
[10,20]<br>
Axis=0<br>
2-d array<br>
Axis =2<br>
Row-axis-0<br>
Coloumn axis-1<br>
<br>____________________<br>

Axis--3<br>
Axis-1 row <br>
Axis-2 coloumn <br>
Axis-3 table<br>






In [ ]:
import numpy as np

In [ ]:
marks=np.array([10,20,30])
print(marks)
print(marks.ndim)

[10 20 30]
1


In [ ]:
marks=np.array([[10,20,30],[40,50,60]])
print(marks)
print(marks.ndim)

[[10 20 30]
 [40 50 60]]
2


In [ ]:
marks=np.array([[[10,20,30],[40,50,60]],[[10,20,30],[40,50,60]]])
print(marks)
print(marks.ndim)

[[[10 20 30]
  [40 50 60]]

 [[10 20 30]
  [40 50 60]]]
3


1-d to 2d

In [ ]:
arr=np.array([10,20,30],ndmin=3)
print(arr)
print(arr.ndim)

[[[10 20 30]]]
3


In [ ]:
arr=np.array([10,20,30],ndmin=2)
print(arr)
print(arr.ndim)

[[10 20 30]]
2


**Attributes**
<br>Shape--> row and coloumn<br>\
Size --> total element<br>
Ndim--> dimension<br>
Dtype--> data type<br>
Item size-->how much byte used one element<ar>
Nbyte--> how much memory used completed array<br>
In memory<br>
Array,Values,Shape,Size,Dimension,DataType,Memory information<br>

In [ ]:
arr=np.array([[10,20,30],[10,20,30],[10,20,30]])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)

(3, 3)
9
2
int64
8
72


In [ ]:
# Special Array
# Arr=[10,20,30,40]



In [ ]:

arr=(np.zeros(50))
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [ ]:
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr=np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr1=np.empty((5,3))
print(arr1)
#O/P = Garbage values

[[6.64081653e-310 4.92471569e-315 3.26444057e+132]
 [2.06477173e+161 1.41902756e+195 6.92680072e+218]
 [1.23762427e+224 1.45977680e+185 6.46336838e+170]
 [1.12044026e+224 6.36832413e+151 6.65796709e-114]
 [1.14531771e+248 5.60176734e+141 6.32404027e-322]]


In [ ]:
arr=np.full((2,3),'Vansh')
print(arr)

[['Vansh' 'Vansh' 'Vansh']
 ['Vansh' 'Vansh' 'Vansh']]


In [ ]:
#np.range
arr=np.arange(1.0,20.0,2)
print(arr)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]


In [ ]:
#linspace
s1=np.linspace(0,10,20)
print(s1)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [ ]:
#Identity matrix

In [ ]:
arr=np.identity(3)
print(arr)
print("Using eye")
arr2=np.eye(3,4) # If we pass k=1 then 1 moves from main diagonal
print(arr2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Using eye
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [ ]:
# Random module- It generates random number, It helps in neural network.
# Pseudo random number generator-algorithm name=Linear Congruential Generator
s=np.random.rand(100)
print(s)


[0.0197779  0.39286075 0.74366538 0.77751344 0.5638817  0.07260765
 0.80001132 0.9712728  0.41779434 0.19822158 0.40818682 0.96731478
 0.6157517  0.99334289 0.26254201 0.40928457 0.71691749 0.79809475
 0.72021732 0.91283372 0.86267427 0.02842818 0.22561919 0.88951715
 0.57627276 0.1191958  0.14233567 0.41669241 0.65804465 0.42727531
 0.51671343 0.34878945 0.17440035 0.86083098 0.35049761 0.29095372
 0.87954527 0.88829469 0.86160529 0.82091152 0.05125325 0.52804756
 0.72626185 0.15725589 0.06322849 0.44581922 0.54991954 0.92540557
 0.86309447 0.54043399 0.55174679 0.34674609 0.23201423 0.84383318
 0.14471133 0.59896276 0.11408767 0.32650829 0.46323988 0.61062034
 0.38414563 0.58693938 0.5404375  0.50288983 0.93550617 0.68665462
 0.0722048  0.35055475 0.03540335 0.72964499 0.63407064 0.09618381
 0.40096123 0.69839308 0.74722818 0.10004465 0.96867642 0.45601667
 0.41451922 0.4730428  0.84297307 0.32345719 0.44148053 0.87543547
 0.98547877 0.04965317 0.59093627 0.45946723 0.52062178 0.4525

In [ ]:
s=np.random.rand(3,3)
print(s)

[[0.69270536 0.55127373 0.29811521]
 [0.40070822 0.65388375 0.02477357]
 [0.05034097 0.1886396  0.43337746]]


In [ ]:
s=np.random.randint(3)
print(s)
s=np.random.randint(1,20,5)
print(s)
# If we take seed value as a input then output not changed.


0
[ 7 18  8  1 13]


In [ ]:
s=np.random.randint(1,7)
s

5

In [ ]:
h=np.random.randn(100)
h
h=np.random.randn(3,3)
h
# Mostly values are near 0&1
#Follows normal distribution.

array([[-1.00142728e-03, -1.87699356e-01,  8.62802961e-01],
       [-1.47235263e+00, -6.95592889e-01,  3.14727008e-01],
       [-1.14444668e-02,  7.43059314e-01,  9.91027234e-01]])

In [ ]:
# Seed value
np.random.seed(20)
f=np.random.rand(5)
print(f)
np.random.seed(30)
f=np.random.randint(20,30)
print(f)
np.random.seed(20)
f=np.random.randn(20,30)
print(f)

[0.5881308  0.89771373 0.89153073 0.81583748 0.03588959]
25
[[ 8.83893113e-01  1.95865022e-01  3.57536516e-01 -2.34326191e+00
  -1.08483259e+00  5.59696289e-01  9.39469350e-01 -9.78481042e-01
   5.03096840e-01  4.06414469e-01  3.23461010e-01 -4.93410882e-01
  -7.92016791e-01 -8.42367934e-01 -1.27950266e+00  2.45715170e-01
  -4.41948007e-02  1.56763255e+00  1.05110868e+00  4.06368426e-01
  -1.68646101e-01 -3.18970279e+00  1.12013226e+00  1.33277821e+00
  -2.43338766e-01 -1.30030711e-01 -1.09017371e-01  1.55618644e+00
   1.28778353e-01 -2.06694872e+00]
 [-8.85493155e-01 -1.10457948e+00  9.32866347e-01  2.05983800e+00
  -9.34937958e-01 -1.61299022e+00  5.27069718e-01 -1.55110074e+00
   3.29613339e-01 -1.13652654e+00 -3.38490605e-01  3.20970784e-01
  -6.02308018e-01  1.54472836e+00  6.47034084e-01  5.93217213e-01
   4.38024497e-01  1.35778902e+00  1.20451128e+00  1.35179619e+00
   4.93437236e-01 -2.70436525e+00 -5.55185797e-01  1.50856026e-03
   8.57093817e-01  1.48114365e+00 -2.19661122e-

In [ ]:
d=np.random.choice([10,20,30,40],size=3,replace=False) # if we dont allow repetetion then use replace
print(d) #replace =True (default)

[20 10 30]


In [ ]:
# We manually define the probability
d=np.random.choice([10,20,30,40],size=4,p=[.5,0.1,.1,.3])
print(d)

[10 10 40 10]


In [ ]:
d=np.array([10,20,30,40,50])
print("d before shuffle",d)
np.random.shuffle(d)
print("d after shuffle",d)

d before shuffle [10 20 30 40 50]
d after shuffle [50 10 30 40 20]


In [ ]:
a=np.array([10,20,30])
print(a.dtype)
a=np.array([10,20.0,30])
print(a.dtype)
a=np.array(["10","20","30000"])
print(a.dtype)

int64
float64
<U5


In [ ]:
arr=np.arange(1,20)
print(arr[0:3])

[1 2 3]


In [ ]:
arr=np.random.randint(1,20,(3,3))
arr[1][2]

np.int64(12)

In [ ]:
arr=np.random.randint(1,20,(3,3,3))
print(arr)
arr[1][1][1]

[[[15  4 15]
  [16 18 13]
  [ 7  2  3]]

 [[18  3  2]
  [ 4 14 13]
  [16 14 13]]

 [[ 3  4 19]
  [11 11 12]
  [ 4 11  4]]]


np.int64(14)

In [ ]:
#Reshaping
arr=np.random.randint(1,20,9)
print(arr)
arr=arr.reshape(3,3)
print(arr)

[ 1 13  6 11 12 11 18 19  2]
[[ 1 13  6]
 [11 12 11]
 [18 19  2]]


In [ ]:
#Flaten
#copy of original and give a one d array
s=np.array([1,2,3,4,5,6])
new_arr=s.flatten()
print(new_arr)
print(s)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
#Ravel-Donot create copy give a one-d array
s=np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
new_arr=s.ravel()
print(new_arr)

[1 2 3 4 5 6 1 2 3 4 5 6]
