<a href="https://colab.research.google.com/github/vanshchaudharyx/Python-Libraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**
<br>Used for mathematical operations
<br>It is fast than list.
<br>p=[10,20,30,40]
<br>Pyhton list --->data large --> slow
<br>Uses More Memory
<br>Mathematical operations are not use direct
<br>------------------------<br>

<br>Numpy array
<br>-->
<br>Fast
<br>Memory effiecient
<br>Machine Learning
<br>Data Science
<br>Deep Learning
<br>Image Processing
<br>Medical Analysis

<br>Python-->numpy function -->C Language Backend --> Fast output
<br>-----------------------------<br>
Colab--> import numpy as np recommended<br>
np.array()-----> important function<br>
python List,Tuple,nested list---> convert in to nd array<br>







In [8]:
import numpy as np

In [ ]:
print (np.__version__)

2.0.2


In [5]:
print(type(np))
# OP----<class 'module'>

<class 'module'>


In [9]:
m=[10,20,30,40,50]

In [10]:
arr=np.array(m)
print(type(m))
arr=np.array(m)
print(arr)
print(type(arr))

<class 'list'>
[10 20 30 40 50]
<class 'numpy.ndarray'>


How to direct list to array

In [11]:
arr=np.array([10,20,30,40,50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [12]:
tup=(10,20,30,40,50)
arr=np.array(tup)
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [13]:
arr=np.array(['Abhi','Rudra','Ram'])
print(arr)

['Abhi' 'Rudra' 'Ram']


In [14]:
list=[10.5,20.5,30.5,40.5,50.5]
arr=np.array(list)
print(arr)
print(type(arr))



[10.5 20.5 30.5 40.5 50.5]
<class 'numpy.ndarray'>


In [15]:
arr=np.array(['Vansh',90000000])
print(arr)

['Vansh' '90000000']
